version: '3.8' 

services: 
  backend:
    build:
      context: ./backend 
    ports:
      - "3000:3000" 
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb+srv://rk3727000:yash3727@cluster0.xtgjz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - ACCESS_TOKEN_SECRET=ravikant12345
      - REFRESH_TOKEN_SECRET=raviyash123321
    
  frontend:
    build:
      context: ./frontend 
      args:
        VITE_BACKENDURL: http://localhost:3000/api/v1
    ports:
      - "80:80" 
    depends_on:
      - backend 